# Generated by Django 5.0 on 2023-12-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='messagesCount',
            new_name='messages_count',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='themesCount',
            new_name='themes_count',
        ),
    ]
