# Generated by Django 5.0 on 2023-12-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abapp', '0002_rename_messagescount_customuser_messages_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='createDate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='themeOwner',
            new_name='theme_owner',
        ),
        migrations.RenameField(
            model_name='thememessage',
            old_name='sendDate',
            new_name='send_date',
        ),
    ]
